add transferring test
openprocurement/openprocurement.auctions.swiftsure pull request #12
Opened 2018-05-29 13:17 UTC by vmotso

2018-05-29 14:44 UTC, Scandie commented on openprocurement/auctions/swiftsure/tests/transferring.py
> +from openprocurement.auctions.flash.tests.base import BaseAuctionWebTest
Кроспроцедурні імпорти тепер допускаються?

2018-05-30 07:29 UTC, bdmbdsm commented on openprocurement/auctions/swiftsure/tests/transferring.py
> +from openprocurement.auctions.flash.tests.base import BaseAuctionWebTest
Думаю, не варто

2018-05-30 07:57 UTC, vmotso commented on openprocurement/auctions/swiftsure/tests/transferring.py
> +from openprocurement.auctions.flash.tests.base import BaseAuctionWebTest
копіпаста(

2018-05-30 11:16 UTC, oleksiyVeretiuk approved these changes

2018-05-30 11:18 UTC, oleksiyVeretiuk requested changes

2018-05-30 11:18 UTC, oleksiyVeretiuk commented on openprocurement/auctions/swiftsure/tests/transferring.py
> +from openprocurement.auctions.flash.tests.base import BaseAuctionWebTest
Такі імпорти заборонені

2018-05-31 06:56 UTC, oleksiyVeretiuk approved these changes

2018-05-31 07:02 UTC, bdmbdsm approved these changes

2018-06-01 10:05 UTC, Scandie approved these changes

2018-06-06 09:56 UTC, merged